name: Deploy to GitHub Pages via angular-cli-ghpages

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps: 
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js v14.15.1
      uses: actions/setup-node@v1
      with:
        node-version: v14.15.1

    - name: Install
      run: |
        npm install
    - name: Assign API_KEY
      env:
        MY_API_KEY: ${{ secrets.MY_API_KEY }}
      run: |
        npm run config 
    - name: Build      
      run: |
       npm run build --base-href="${{ secrets.MY_HREF }}"
    - name: Deploy
      run: |
       npm run ghpages --name="MG" --email="michal.gwozdz2@gmail.com"