name: Deploy to GitHub Pages via angular-cli-ghpages

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js v14.15.1
      uses: actions/setup-node@v1
      with:
        node-version: v14.15.1

    - name: Install
      run: |
        npm install
    - name: Assign API_KEY
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        echo 1: ${{ env.API_KEY }}
        echo 2: ${{ secrets.API_KEY }}
        echo 3: ${{ process.env.API_KEY }}
        npm run config ${{ secrets.API_KEY }}
    - name: Build
      run: |
       npm run build --prod --base-href="https://michalgwozdz2.github.io/backbase-weather/"