name: Deploy to GitHub Pages via angular-cli-ghpages

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js v14.15.1
      uses: actions/setup-node@v1
      with:
        node-version: v14.15.1

    - name: Prepare and deploy
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        npm install
        npm run config
        npm run build --prod --base-href "https://michalgwozdz2.github.io/backbase-weather/"